# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Setting

# Model Form Field configuration
form: $/suresoftware/powerblog/models/setting/fields.yaml

# Model Class name
modelClass: SureSoftware\PowerBlog\Models\Setting

# Default redirect location
defaultRedirect: suresoftware/powerblog/settings

# Create page
create:
    title: Create Setting
    redirect: suresoftware/powerblog/settings/update/:id
    redirectClose: suresoftware/powerblog/settings

# Update page
update:
    title: Edit Setting
    redirect: suresoftware/powerblog/settings
    redirectClose: suresoftware/powerblog/settings

# Preview page
preview:
    title: Preview Setting
